version: "3.9"
services:
 
  # Prefect UI (Orion)
  prefect:
    image: prefecthq/prefect:2-python3.10
    restart: always
    volumes:
      - ./prefect:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
    ports:
      - 4200:4200
    networks:
      - monitoring
  
networks:
  monitoring:
    name: monitoring